spring.application.name=gmao-backend

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3307/gmao_mobility}
spring.datasource.username=gmao_user
spring.datasource.password=${DB_PASSWORD} 
jwt.secret=${JWT_SECRET} 
app.superadmin.password=${SUPERADMIN_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8090


jwt.expiration=86400000
app.upload-dir=uploads

# Compte SUPERADMIN créé automatiquement au premier démarrage
# (uniquement si aucun SUPERADMIN n'existe déjà en base).
app.superadmin.email=superadmin@gmao.local

app.superadmin.first-name=Super
app.superadmin.last-name=Admin
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB